### ISSUE TITLE
Adicionado o AUTHORS

### ISSUE THREAD

**Issue by iWarhead** [alessonrenato/discreta07grp01#2]
Senhores(as) por favor confirmem seus nomes no arquivo AUTHORS, obrigado.

**Comment by alessonrenato** [comment]
o meu ta ok

**Comment by wagner-lucas** [comment]
ta ok

**Comment by hgees** [comment]
Tudo certo no de vcs

**Comment by hgees** [comment]
E no meu tb

**Comment by aronsales** [comment]
O meu estava errado, ja foi corrigido e está ok.

**Comment by caahreginaa** [comment]
O meu tá OK.

**Comment by RafaelRSPX** [comment]
Certo. Tudo ok.
